### ISSUE TITLE
Python blobmap segfault

### ISSUE THREAD

**Issue by mouuff** [quarkslab/binmap#15]
The code below segfaults (I believe you can use any *.dat file to reproduce this bug)

```
import blobmap
f = blobmap.BlobMap("./test/local.dat")
f[0]
```

I think it should return a python error instead

**Comment by serge-sans-paille** [comment]
I can reproduce, thanks for reporting

**Comment by serge-sans-paille** [comment]
@mouuff can you confirm #16 fixes your issue?

**Comment by mouuff** [comment]
I confirm your changes have fixed the segfault
Thanks for the fix

**Comment by serge-sans-paille-qb** [comment]
great closing the issue
