### ISSUE TITLE
view.predecessors Segfault

### ISSUE THREAD

**Issue by mouuff** [quarkslab/binmap#17]
This bug report is pretty similar to the one I wrote last week

The code below segfaults (I believe you can use any *.dat file to reproduce this bug)
```
blob = blobmap.BlobMap("./test/local.dat")
view = next(blob.values())
view.predecessors("does_not_exists")
```
I think it should return a python error instead

**Comment by serge-sans-paille-qb** [comment]
Should be fixed by #18
