### ISSUE TITLE
Multiple keys, same library, different predecessors

### ISSUE THREAD

**Issue by mouuff** [quarkslab/binmap#19]
Hello,

I don't understand why binmap have multiple keys for one library.
my guess is: you check ELF 'needed libraries' and add it to the graph.
Which means: when they have different name there is different keys, even if the hash is the same.
Which is logic considering there is often symlinks for libraries, and you follow symlinks.

But there is also a key created for each dependency of any elf file (resolved or not), and the metadata of this key have a hash string which I don't know where it comes from, and it has an empty name, and empty version, and when calling `view.predecessors` on this type of key: there is different results on the same library with different names on the system.
My guess is you use this key to make your graph easily using pure dependency name.

This means : For the same library there is different result when calling `view.predecessors`

With that said, I don't understand why you have both absolute path to libraries, and pure dependency name of the library in the graph, and with different predecessors.

Case of use:
I want the predecessors of libz.so.1
- I must find myself all the others libz.so on the system, but I can't with the hash because this one could be wrong
- I must call view.predecessors for each libz.so.1 I have found.

Another solution would be to do the merge myself in order to clean up the graph:
Example:
If I have this keys ['libz.so.1', '/usr/main/local/lib/libz.so.1', '/usr/main/local/lib/libz.so.1.2.8', '/usr/main/local/lib/libz.so']
I must merge all of it into one key. (libz.so.1) and do the same for all other keys, in order to recreate a "clean" graph.

It really sounds weird to me to have this kind of behavior considering goal of binmap
Am I doing anything wrong? If no have you planned to change this behavior or are you open to such additions/modifications to binmap?

**Comment by serge-sans-paille-qb** [comment]
Correct me if i'm wrong: you have a problem with libz that are not associated to a path, because binmap could not find a way to resolve the dynamic binding statically.

I

There could be two different versions of libz in the system, one in a standard location, and one in another location, one being modified etc...

> I don't understand why you have both absolute path to libraries, and pure dependency name of the library in the graph, and with different predecessors.

The one with a path were statically resolved, the others could not

> I must find myself all the others libz.so on the system,

what about

```python
libzs = [k for k in view.keys() where re.match(r'.*libz.*;so', k)] # not very robust
```
and then start from there?

> If I have this keys ['libz.so.1', '/usr/main/local/lib/libz.so.1', '/usr/main/local/lib/libz.so.1.2.8', '/usr/main/local/lib/libz.so']
I must merge all of it into one key. (libz.so.1) and do the same for all other keys, in order to recreate a "clean" graph.

I would do it that way, yes.

**Comment by mouuff** [comment]
Thank you for your fast answer.
Can you think of any proper/robust way to get the right hash from the base name of the library?
