### ISSUE TITLE
"chroot" scanning

### ISSUE THREAD

**Issue by trou** [quarkslab/binmap#2]
Nice tool :)

It'd be even nicer to be able to restrict dependency lookup to a specific root. It'd be particularly useful for scanning extracted filesystems.

For example:
`./binscan scan -R extracted_fs/`
would consider a reference to `/lib/ld.so` as `extracted_fs/lib/ld.so`

**Comment by serge-sans-paille** [comment]
Oh, you're speaking about the ``--chroot`` feature, that appears to be undocumented in the readme :-) I'll add a word about it.

**Comment by serge-sans-paille** [comment]
@trou can you review  #3 that improves the doc relative to the ``--chroot`` flag?

**Comment by trou** [comment]
Thx.
