### ISSUE TITLE
blobmap module

### ISSUE THREAD

**Issue by hardboost** [quarkslab/binmap#7]
It's maybe dumb question, but where i can get blobmap module for python? 
i believe "blobmap.dll" is the module but i don't know how to install it to python.

**Comment by serge-sans-paille** [comment]
It should leave somewhere in the build directory. Under Linux, it's directly in the build directory (``_build/blobmap.so`` if cmake was run in ``_build``). To use it one must be in the same directory and run ``python -c 'import blobmap'`` which should not fail if everything is ok. Otherwise set the PYTHONPATH in an appropriate way. I let @neitsa describe his setup on windows ;-)

**Comment by hardboost** [comment]
```
C:\Tools\binmap\Debug>dir | findstr "blobmap"
04.05.2016  18:37         1 751 040 blobmap.dll
04.05.2016  18:37           254 031 blobmap.exp
04.05.2016  18:37         8 896 588 blobmap.ilk
04.05.2016  18:37           326 970 blobmap.lib
04.05.2016  18:37        26 292 224 blobmap.pdb

C:\Tools\binmap\Debug>python -c "import blobmap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named blobmap
```
will wait for @neitsa's help

**Comment by neitsa** [comment]
The setup is somewhat contrived on Windows.

**Note**: 
    - I have built a  debug version of the binmap solution
    - My build directory is on `G:\Work\GIT\binmap-build\Debug>`

1) Rename the `blobmap.dll` to `blobmap.pyd` (on windows you can't load .dll files with the python interpreter, you need to rename them to `*.pyd`):

    G:\Work\GIT\binmap-build\Debug>copy blobmap.dll blobmap.pyd
        1 file(s) copied.

2) Check which DLLs are imported by the blobmap.dll module (this depends on your build type [release | debug] and on your Boost version. We want to know which **Boost DLLs** are imported by the **blobmap.pyd** module . I'm using a tool called `CFF explorer` to do this:

Usually we have (debug version here, hence the 'd' in `mt-gd`):

    - boost_filesystem-vcXXX-mt-gd-1_XX.dll
    - boost_filesystem-vcXXX-mt-gd-1_XX.dll
    - boost_serialization-vcXXX-mt-gd-1_XX.dll
    - boost_system-vcXXX-mt-gd-1_XX.dll

![image](https://cloud.githubusercontent.com/assets/4538670/15044706/a345a398-12d6-11e6-8ca5-70cff1eed9a4.png)

3) Once you have those DLL names, copy them (from your boost binary directory) alongside the `blobmap.pyd` module (e.g. in my case in the `G:\Work\GIT\binmap-build\Debug` directory). Make sure you use the right binaries (e.g. x86 if your build and python interpreter are x86):

![image](https://cloud.githubusercontent.com/assets/4538670/15044821/5794a952-12d7-11e6-999b-3d6e4e6adfd5.png)

4) start a command prompt (`cmd.exe`) in the `blobmap.pyd` directory (e.g. `G:\Work\GIT\binmap-build\Debug`) and set it as your `PYTHONPATH` environment variable:

    G:\Work\GIT\binmap-build\Debug>set PYTHONPATH=G:\Work\GIT\binmap-build\Debug

5) Start python and import blobmap, you should have no error:

Note that I have multiple python versions installed with the default (`py.exe`) launcher. Starting the python interpreter right away from the command line is also fine.

    G:\Work\GIT\binmap-build\Debug>py -2.7-32
    Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
    Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import blobmap
    >>>

Let us know if that works :)

[speaking of which, we should have auto renamed `blobmap.dll` to `blobmap.pyd` on windows and and done a more detailed explanation on how to proceed with the Windows' installation. We'll do it ASAP.]

**Comment by hardboost** [comment]
@neitsa thank you! that works :)

**Comment by serge-sans-paille** [comment]
@hardboost I just pushed a commit to prevent the need of manual copy, if you can check that the updated version of the PR fixes this part for your case?
